pipeline {
    agent any
    stages {
        stage('Greeting') {
            steps {
                library 'my-shared-library'
                echo "Executing step"
                script {
                    // Call the default function
                    greet('Jenkins')

                    // Call the farewell function
                    greet.farewell('Jenkins')

                    // Call the personalizedGreeting function
                    greet.personalizedGreeting('Jenkins', 'Hope you are enjoying Jenkins!')
                }
            }
        }
    }
}

